add new test and change user var name

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -66,7 +66,7 @@ jobs:
           sleep 1
         env:
           POSTGRES_PWD: test
-          USER: test
+          DBUSER: test
           DATABASE: testdb
           HOST: 127.0.0.1
 
@@ -94,6 +94,19 @@ jobs:
             exit 1  # Fail the GitHub Action
           fi
 
+      - name: Test New
+        run: |
+          PATTERN='^\{?[A-Z0-9a-z]{8}-[A-Z0-9a-z]{4}-[A-Z0-9a-z]{4}-[A-Z0-9a-z]{4}-[A-Z0-9a-z]{12}\}?$'
+          OUTPUT=$(go run -C taskcli/ . new -t 'Title test task' -d 'Desc test task' 2>&1)
+
+          if [[ "$OUTPUT" =~ $PATTERN ]]; then
+            echo "Test: new passed"
+          else
+            echo "Test: new failed!" >&2
+            echo "Output: $OUTPUT is not what is expected"
+            exit 1 # Fail the GitHub Action
+          fi
+          
       - name: Test Get 
         run: |
           OUTPUT=$(go run -C taskcli/ . get 2>&1 | jq 'length')
