Update test del

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -94,27 +94,27 @@ jobs:
             exit 1  # Fail the GitHub Action
           fi
 
-      - name: Test New
-        run: |
-          PATTERN='^\{?[A-Z0-9a-z]{8}-[A-Z0-9a-z]{4}-[A-Z0-9a-z]{4}-[A-Z0-9a-z]{4}-[A-Z0-9a-z]{12}\}?$'
-          OUTPUT=$(go run -C taskcli/ . new -t 'Title test task' -d 'Desc test task' 2>&1)
-
-          if [[ "$OUTPUT" =~ $PATTERN ]]; then
-            echo "Test: new passed"
-          else
-            echo "Test: new failed!" >&2
-            echo "Output: $OUTPUT is not what is expected"
-            exit 1 # Fail the GitHub Action
-          fi
-          
       - name: Test Get 
         run: |
           OUTPUT=$(go run -C taskcli/ . get 2>&1 | jq 'length')
 
-          if [ "$OUTPUT" = 3 ]; then
+          if [ "$OUTPUT" = 2 ]; then
             echo "Test: get passed"
           else
             echo "Test: get failed!" >&2
+            echo "Output: $OUTPUT is not what is expected, there should be 2 tasks"
+            exit 1  # Fail the GitHub Action
+          fi
+
+      - name: Test New
+        run: |
+          go run -C taskcli/ . new -t 'Title test task' -d 'Desc test task'
+          OUTPUT=$(go run -C taskcli/ . get 2>&1 | jq 'length')
+
+          if [ "$OUTPUT" = 3 ]; then
+            echo "Test: new passed"
+          else
+            echo "Test: new failed!" >&2
             echo "Output: $OUTPUT is not what is expected, there should be 3 tasks"
             exit 1  # Fail the GitHub Action
           fi
@@ -149,7 +149,7 @@ jobs:
           go run -C taskcli/ . del --id '33333333-3333-3333-3333-333333333333'
           OUTPUT=$(go run -C taskcli/ . get 2>&1 | jq 'length')
 
-          if [ "$OUTPUT" = 1 ]; then
+          if [ "$OUTPUT" = 2 ]; then
             echo "Test: del passed"
           else
             echo "Test: del failed!" >&2
